Enemies = {
    "docmercy": ["GD_Population_Nomad.Balance.Unique.PawnBalance_MrMercy", "Frost_Dynamic", "Basegame"],
    "muscles": ["GD_Population_Bruiser.Balance.PawnBalance_Bruiser_Muscles", "Grass_Cliffs_Combat", "Basegame"],
    "badasscreeper": ["GD_Population_Creeper.Balance.PawnBalance_CreeperBadass", "Caverns_P", "Basegame"],
    "hunterhellquist": ["GD_Population_Engineer.Balance.Unique.PawnBalance_DJHyperion", "Fyrestone_Dynamic", "Basegame"],
    "foremanrusty": ["GD_Population_Engineer.Balance.Unique.PawnBalance_Foreman", "HyperionCity_Dynamic", "Basegame"],
    "gettle": ["GD_Population_Engineer.Balance.Unique.PawnBalance_Gettle", "Interlude_Dynamic", "Basegame"],
    "smashhead": ["GD_Population_Goliath.Balance.Unique.PawnBalance_SmashHead", "Fridge_Dynamic", "Basegame"],
    "bonehead2": ["GD_Population_Loader.Balance.Unique.PawnBalance_BoneHead2", "Stockade_Combat", "Basegame"],
    "assassinwot": ["GD_Population_Marauder.Balance.Unique.PawnBalance_Assassin1", "SouthpawFactory_Dynamic", "Basegame"],
    "assassinoney": ["GD_Population_Nomad.Balance.Unique.PawnBalance_Assassin2", "SouthpawFactory_Dynamic", "Basegame"],
    "assassinreeth": ["GD_Population_Psycho.Balance.Unique.PawnBalance_Assassin3", "SouthpawFactory_Dynamic", "Basegame"],
    "assassinrouf": ["GD_Population_Rat.Balance.Unique.PawnBalance_Assassin4", "SouthpawFactory_Dynamic", "Basegame"],
    "mickzaford": ["GD_Population_Marauder.Balance.Unique.PawnBalance_MickZaford_Combat", "Interlude_Dynamic", "Basegame"],
    "tectorhodunk": ["GD_Population_Marauder.Balance.Unique.PawnBalance_TectorHodunk_Combat", "Interlude_Dynamic", "Basegame"],
    "mobley": ["GD_Population_Marauder.Balance.Unique.PawnBalance_Mobley", "Interlude_Dynamic", "Basegame"],
    "badmaw": ["GD_Population_Nomad.Balance.PawnBalance_BadMaw", "Frost_Dynamic", "Basegame"],
    "madmike": ["GD_Population_Nomad.Balance.Unique.PawnBalance_MadMike", "Dam_Combat", "Basegame"],
    "prospectorzeke": ["GD_Population_Nomad.Balance.Unique.PawnBalance_Prospector", "TundraExpress_Combat", "Basegame"],
    "steve": ["GD_Population_NPC.Balance.PawnBalance_NPC_Steve", "Interlude_Dynamic", "Basegame"],
    "donkeymong": ["GD_Population_PrimalBeast.Balance.Unique.PawnBalance_PrimalBeast_DonkeyMong", "Ash_Combat", "Basegame"],
    "kingmong": ["GD_Population_PrimalBeast.Balance.Unique.PawnBalance_PrimalBeast_KingMong", "Ash_Combat", "Basegame"],
    "midgemong": ["GD_Population_PrimalBeast.Balance.Unique.PawnBalance_PrimalBeast_Warmong", "Cove_Dynamic", "Basegame"],
    "incineratorclayton": ["GD_Population_Psycho.Balance.Unique.PawnBalance_IncineratorVanya_Combat", "IceCanyon_Combat", "Basegame"],
    "maddog": ["GD_Population_Psycho.Balance.Unique.PawnBalance_MadDog", "Grass_Lynchwood_Combat", "Basegame"],
    "mcnally": ["GD_Population_Psycho.Balance.Unique.PawnBalance_McNally", "Interlude_Combat", "Basegame"],
    "rakkman": ["GD_Population_Psycho.Balance.Unique.PawnBalance_RakkMan", "Fridge_Combat", "Basegame"],
    "savagelee": ["GD_Population_Psycho.Balance.Unique.PawnBalance_SavageLee", "Ice_Dynamic", "Basegame"],
    "sonofmothrakk": ["GD_Population_Rakk.Balance.Unique.PawnBalance_SonMothrakk", "PandoraPark_Combat", "Basegame"],
    "dan": ["GD_Population_Rat.Balance.Unique.PawnBalance_Dan", "Dam_Dynamic", "Basegame"],
    "lee": ["GD_Population_Rat.Balance.Unique.PawnBalance_Lee", "Dam_Dynamic", "Basegame"],
    "mick": ["GD_Population_Rat.Balance.Unique.PawnBalance_Mick", "Dam_Dynamic", "Basegame"],
    "ralph": ["GD_Population_Rat.Balance.Unique.PawnBalance_Ralph", "Dam_Dynamic", "Basegame"],
    "flinter": ["GD_Population_Rat.Balance.Unique.PawnBalance_RatEasterEgg", "Dam_Dynamic", "Basegame"],
    "laneywhite": ["GD_Population_Rat.Balance.Unique.PawnBalance_Laney", "Fridge_Dynamic", "Basegame"],
    "mortar": ["GD_Population_Rat.Balance.Unique.PawnBalance_Mortar", "CraterLake_Dynamic", "Basegame"],
    "sheriffoflynchwood": ["GD_Population_Sheriff.Balance.PawnBalance_Sheriff", "Grass_Lynchwood_Dynamic", "Basegame"],
    "dukinosmom": ["GD_Population_Skag.Balance.Unique.PawnBalance_Skagzilla", "Grass_Lynchwood_Dynamic", "Basegame"],
    "pimon": ["GD_Population_Stalker.Balance.Unique.PawnBalance_Stalker_Simon", "PandoraPark_Combat", "Basegame"],
    "tumbaa": ["GD_Population_Skag.Balance.Unique.PawnBalance_Tumbaa", "PandoraPark_Combat", "Basegame"],
    "blackqueen": ["GD_Population_SpiderAnt.Balance.Unique.PawnBalance_SpiderantBlackQueen", "Interlude_Combat", "Basegame"],
    "scorch": ["GD_Population_SpiderAnt.Balance.Unique.PawnBalance_SpiderantScorch", "IceCanyon_Combat", "Basegame"],
    "henry": ["GD_Population_Stalker.Balance.Unique.PawnBalance_Henry", "Grass_Dynamic", "Basegame"],
    "oldslappy": ["GD_Population_Thresher.Balance.Unique.PawnBalance_Slappy", "Outwash_Dynamic", "Basegame"],
    "boll": ["GD_Z1_InMemoriamData.Balance.PawnBalance_Boll", "Ice_Dynamic", "Basegame"],
    "madamevonbartlesby": ["GD_Population_BugMorph.Balance.Unique.PawnBalance_SirReginald", "TundraExpress_Dynamic", "Basegame"],
    "spycho": ["GD_Population_SpiderAnt.Balance.Unique.PawnBalance_MonsterMash1", "IceCanyon_Dynamic", "Basegame"],
    "w4rd3n": ["GD_Population_Constructor.Balance.Unique.PawnBalance_ConstructorRoland", "HypInterlude_P", "Basegame"],
    "blue": ["GD_Population_Crystalisk.Balance.Unique.PawnBalance_Blue", "Caverns_Dynamic", "Basegame"],
    "warlordgrug": ["GD_Aster_Pop_Orcs.Balance.PawnBalance_Orc_WarlordGrug", "Dark_Forest_Combat", "Aster"],
    "warlordslog": ["GD_Aster_Pop_Orcs.Balance.PawnBalance_Orc_WarlordSlog", "TempleSlaughter_Combat", "Aster"],
    "warlordturge": ["GD_Aster_Pop_Orcs.Balance.PawnBalance_Orc_WarlordTurge", "Mines_Combat", "Aster"],
    "spiderpants": ["GD_Aster_Pop_Spiders.Unique.PawnBalance_Spiderpants", "Mines_Combat", "Aster"],
    "ltbolson": ["GD_Anemone_Pop_NP.Balance.PawnBalance_Lt_Bolson", "OldDust_Mission_Side", "Anemone"],
    "ltangvar": ["GD_Anemone_Pop_NP.Balance.PawnBalance_NP_Lt_Angvar", "Sandworm_Mission_Side", "Anemone"],
    "lthoffman": ["GD_Anemone_Pop_NP.Balance.PawnBalance_NP_Lt_Hoffman", "ResearchCenter_MissionSide", "Anemone"],
    "lttetra": ["GD_Anemone_Pop_NP.Balance.PawnBalance_NP_Lt_Tetra", "Helios_Mission_Side", "Anemone"],
    "sonofflynt": ["GD_FlyntSon.Population.PawnBalance_FlyntSon_Run", "Easter_Mission_Side", "Nasturtium"],
    "sullythestabber": ["GD_Iris_Population_Marauder.Balance.Iris_PawnBalance_SullyTheStabber", "Iris_DL2_Combat", "Iris"],
    "nobeard": ["GD_Orchid_Pop_NoBeard.PawnBalance_Orchid_NoBeard", "Orchid_OasisTown_Combat", "Orchid"],
    "roscoe": ["GD_Orchid_Pop_RakkHive.Character.PawnBalance_Orchid_RakkHive", "Orchid_WormBelly_Dynamic", "Orchid"],
    "clark": ["GD_UndeadFirePsycho_Giant.Balance.PawnBalance_UndeadFirePsycho_Giant", "Pumpkin_Patch_P", "Flax"],
    "sullytheblacksmith": ["GD_Spycho.Population.PawnBalance_Spycho", "Pumpkin_Patch_Dynamic", "Flax"],
    "arizona": ["GD_Sage_Pop_Drifter.Balance.PawnBalance_DrifterNamed", "Sage_Underground_Combat", "Sage"],
    "bulstoss": ["GD_Sage_SM_AcquiredTasteData.Creature.PawnBalance_Sage_AcquiredTaste_Creature", "Sage_Underground_Combat", "Sage"],
    "rouge": ["GD_Sage_SM_BigFeetData.Creature.Population.PawnBalance_Sage_BigFeet_Creature", "Sage_Cliffs_Dynamic", "Sage"],
    "dermonstrositat": ["GD_Sage_SM_BorokCageData.Population.PawnBalance_Sage_BorokCage_Creature", "Sage_Underground_Combat", "Sage"],
    "rakkanoth": ["GD_Sage_SM_DahliaMurderData.Population.PawnBalance_Sage_DahliaMurder_Creature", "Sage_RockForest_Dynamic", "Sage"],
    "dribbles": ["GD_Sage_SM_FollowGlowData.Creature.PawnBalance_Sage_FollowGlow_Creature", "Sage_PowerStation_Combat", "Sage"],
    "bloodtail": ["GD_Sage_SM_NowYouSeeItData.Creature.PawnBalance_Sage_NowYouSeeIt_Creature", "Sage_Cliffs_Combat", "Sage"],


    "wilhelm": ["GD_Population_Loader.Balance.Unique.PawnBalance_Willhelm", "TundraTrain_Dynamic", "Basegame"],
    "boom": ["GD_Population_Marauder.Balance.PawnBalance_BoomBoom", "SouthernShelf_Dynamic", "Basegame"],
    "bewm": ["GD_Population_Marauder.Balance.PawnBalance_Boom", "SouthernShelf_Dynamic", "Basegame"],
    "captainflynt": ["GD_Population_Nomad.Balance.Unique.PawnBalance_Flynt", "SouthernShelf_Dynamic", "Basegame"],
    "knuckledragger": ["GD_Population_PrimalBeast.Balance.Unique.PawnBalance_PrimalBeast_KnuckleDragger", "Glacial_Dynamic", "Basegame"],
    "bnk3r": ["GD_HyperionBunkerBoss.Balance.PawnBalance_HyperionBunkerBoss", "Boss_Cliffs_Combat", "Basegame"],
    "saturn": ["GD_Population_Loader.Balance.Unique.PawnBalance_LoaderGiant", "Stockade_Combat", "Basegame"],
    "mrboneypantsguy": ["GD_Aster_Pop_Skeletons.Balance.PawnBalance_BoneyPants", "Docks_Mission", "Aster"],
    "skeletonking": ["GD_Aster_Pop_Skeletons.Balance.PawnBalance_SkeletonKing_Aliah", "Dead_Forest_Combat", "Aster"],
    "hector": ["GD_Anemone_Hector.PawnBalance_Anemone_Hector", "GaiusSanctuary_MissionMain", "Anemone"],
    "cassius": ["GD_Anemone_Pop_Cassius.PawnBalance_Anemone_Cassius", "ResearchCenter_MissionMain", "Anemone"],
    "uranus": ["GD_Anemone_Population_Loader.Balance.Unique.PawnBalance_Uranus", "Helios_Mission_Main", "Anemone"],
    "blimp": ["GD_Iris_Population_BlimpBoss.Balance.Iris_PawnBalance_BlimpBoss", "Iris_DL3_Combat", "Iris"],
    "motormama": ["GD_Iris_Population_MotorMama.Balance.Iris_PawnBalance_MotorMama", "Iris_Hub2_Combat", "Iris"],
    "piston": ["GD_Iris_Population_PistonBoss.Balance.Iris_PawnBalance_PistonBoss", "Iris_DL1_TAS_Combat", "Iris"],
    "herle": ["GD_Orchid_Pop_LoaderBoss.Balance.PawnBalance_Orchid_LoaderBoss", "Orchid_Refinery_Dynamic", "Orchid"],
    "pumpkinkingpin": ["GD_Pumpkinhead.Population.PawnBalance_Pumpkinhead", "Pumpkin_Patch_Boss", "Flax"],
    "tindersnowflake": ["GD_Snowman.Population.PawnBalance_SnowMan_HARD", "Xmas_Boss", "Allium"],


    "vermi": ["GD_Population_BugMorph.Balance.PawnBalance_BugMorphRaid", "Caverns_P", "Basegame"],
    "terra": ["GD_Population_Thresher.Balance.Unique.PawnBalance_ThresherRaid", "ThresherRaid_P", "Basegame"],
    "bluedragon": ["GD_Aster_Pop_Dragons.Balance.PawnBalance_Dragon_Blue_Raid", "DungeonRaid_Combat", "Aster"],
    "reddragon": ["GD_Aster_Pop_Dragons.Balance.PawnBalance_Dragon_Red_Raid", "DungeonRaid_Combat", "Aster"],
    "greendragon": ["GD_Aster_Pop_Dragons.Balance.PawnBalance_Dragon_Green_Raid", "DungeonRaid_Combat", "Aster"],
    "purpledragon": ["GD_Aster_Pop_Dragons.Balance.PawnBalance_Dragon_Purple_Raid", "DungeonRaid_Combat", "Aster"],
    "pyropete": ["GD_Iris_Population_RaidPete.Balance.Iris_PawnBalance_RaidPete", "Iris_DL2_Interior_Raid", "Iris"],
    "omgwth": ["GD_Population_SpiderTank.Boss.PawnBalance_SpiderTank_Boss", "TestingZone_Combat", "Lobelia"],
    "dexi": ["GD_Sage_Pop_Drifter.Balance.PawnBalance_DrifterRaid", "Sage_Underground_Combat", "Sage"],
}

Chubbies = {
    "varkid": ["GD_Population_BugMorph.Balance.PawnBalance_BugMorphChubby", "Caverns_P", "Basegame"],
    "midget": ["GD_Population_Midget.Balance.PawnBalance_MidgetChubby", "BanditSlaughter_Combat", "Basegame"],
    "rakk": ["GD_Population_Rakk.Balance.PawnBalance_RakkChubby", "Ash_Combat", "Basegame"],
    "skag": ["GD_Population_Skag.Balance.PawnBalance_SkagChubby", "Ice_Dynamic", "Basegame"],
    "spiderant": ["GD_Population_SpiderAnt.Balance.PawnBalance_SpiderantChubby", "Caverns_P", "Basegame"],
    "stalker": ["GD_Population_Stalker.Balance.PawnBalance_StalkerChubby", "Fridge_Combat", "Basegame"],
    "bones": ["GD_Aster_Pop_Skeletons.Balance.PawnBalance_SkeletonChubby", "Village_Dynamic", "Aster"],

}

lootbois = {
    "combatengineer": ["GD_Population_Midget.Balance.LootMidget.PawnBalance_LootMidget_CombatEngineer", "FinalBossAscent_Dynamic", "Basegame"],
    "engineer": ["GD_Population_Midget.Balance.LootMidget.PawnBalance_LootMidget_Engineer", "FinalBossAscent_Dynamic", "Basegame"],
    "goliath": ["GD_Population_Midget.Balance.LootMidget.PawnBalance_LootMidget_Goliath", "BanditSlaughter_Combat", "Basegame"],
    "gunloader": ["GD_Population_Midget.Balance.LootMidget.PawnBalance_LootMidget_LoaderGUN", "FinalBossAscent_Dynamic", "Basegame"],
    "jetloader": ["GD_Population_Midget.Balance.LootMidget.PawnBalance_LootMidget_LoaderJET", "FinalBossAscent_Dynamic", "Basegame"],
    "warloader": ["GD_Population_Midget.Balance.LootMidget.PawnBalance_LootMidget_LoaderWAR", "FinalBossAscent_Dynamic", "Basegame"],
    "marauder": ["GD_Population_Midget.Balance.LootMidget.PawnBalance_LootMidget_Marauder", "Interlude_P", "Basegame"],
    "nomad": ["GD_Population_Midget.Balance.LootMidget.PawnBalance_LootMidget_Nomad", "BanditSlaughter_Combat", "Basegame"],
    "psycho": ["GD_Population_Midget.Balance.LootMidget.PawnBalance_LootMidget_Psycho", "BanditSlaughter_Combat", "Basegame"],
    "rat": ["GD_Population_Midget.Balance.LootMidget.PawnBalance_LootMidget_Rat", "BanditSlaughter_Combat", "Basegame"]
}