
PackageInteractive = ["/Game/InteractiveObjects/ExplodingBarrels/Global/BP_ExplodingObject_Barrel_Proximity",
"/Game/InteractiveObjects/GameSystemMachines/VendingMachine/_Shared/Blueprints/BP_VendingMachine_Ammo",
"/Game/InteractiveObjects/GameSystemMachines/VendingMachine/_Shared/Blueprints/BP_VendingMachine_Health",
"/Game/InteractiveObjects/GameSystemMachines/VendingMachine/_Shared/Blueprints/BP_VendingMachine_Weapons",
"/Game/PatchDLC/Ixora2/InteractiveObjects/GameSystemMachines/VendingMachine/_Shared/BP_VendingMachine_BlackMarket"]

PackageNameInteractive = ["/Game/InteractiveObjects/ExplodingBarrels/Global/BP_ExplodingObject_Barrel_Proximity.BP_ExplodingObject_Barrel_Proximity_C",
"/Game/InteractiveObjects/GameSystemMachines/VendingMachine/_Shared/Blueprints/BP_VendingMachine_Ammo.BP_VendingMachine_Ammo_C",
"/Game/InteractiveObjects/GameSystemMachines/VendingMachine/_Shared/Blueprints/BP_VendingMachine_Health.BP_VendingMachine_Health_C",
"/Game/InteractiveObjects/GameSystemMachines/VendingMachine/_Shared/Blueprints/BP_VendingMachine_Weapons.BP_VendingMachine_Weapons_C",
"/Game/PatchDLC/Ixora2/InteractiveObjects/GameSystemMachines/VendingMachine/_Shared/BP_VendingMachine_BlackMarket.BP_VendingMachine_BlackMarket_C"]
